# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d0661f2bf35b6ee56a0054144f0b3b6789864e6dab290c4b325951da40e804765d2e56c5b0663c14397820e9a78bb79174748950192280bab9657bfcf4e75ef0

test:
  secret_key_base: a2479c23e6010b3bbd46ada41c4fca9a76b7e41fe0b38c6f7b921fa1a8ff96bfd3da79becad8fb90106c512b7627a9eb87979cc580c4ba1c37b946cffbace321

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
